export const VIEWEMPLOYEE = "VIEWEMPLOYEE";
export const ADDEMPLOYEE = "ADDEMPLOYEE";
export const DELETEEMPLOYEE = "DELETEEMPLOYEE";
export const EDITEMPLOYEE = "EDITEMPLOYEE";
export const UPDATEEMPLOYEE = "UPDATEEMPLOYEE";
